name: NaiBlog
title: NaiBlog | Binge Read.
description: Naiblog is inspired by Netflix site, since most of us love to binge watch. So why not binge read over here!!
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
email: jeffubayi@gmail.com
disqus_username: jeffubayi
